# Podfile
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, '13.4'  # Minimum iOS sürümünü burada belirleyebilirsiniz
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'ArdyMobileApp' do
  config = use_native_modules!

  # Hermes'i devre dışı bırakıyoruz
  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    :hermes_enabled => false, # Hermes devre dışı
  )

  # react-native-push-notification için gerekli bağımlılığı ekleyin
  pod 'RNCPushNotificationIOS', :path => '../node_modules/@react-native-community/push-notification-ios'

  # Diğer ek kütüphaneler burada eklenebilir
  # pod 'ReactNativeAsyncStorage', :path => '../node_modules/@react-native-async-storage/async-storage'

  target 'ArdyMobileAppTests' do
    inherit! :complete
    # Test bağımlılıkları
  end

  post_install do |installer|
    # React Native için gerekli post_install işlemleri
    react_native_post_install(installer, config[:reactNativePath])

    # Build ayarları düzeltmeleri
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['ENABLE_BITCODE'] = 'NO' # Bitcode devre dışı
        config.build_settings['DEBUG_INFORMATION_FORMAT'] = 'dwarf-with-dsym' # dSYM dosyalarını oluştur
      end
    end
  end
end
